# Generated by Django 5.0.7 on 2025-03-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_userprofile_selected_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommended_courses',
            field=models.ManyToManyField(blank=True, related_name='recommended_to_users', to='recommend.course'),
        ),
    ]
