# Generated by Django 5.0.7 on 2025-03-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_userprofile_recommended_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='recommend.course'),
        ),
    ]
