# Generated by Django 5.0.7 on 2025-04-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_course_is_removed_userprofile_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_courses',
            field=models.ManyToManyField(blank=True, related_name='selected_by_users', to='recommend.course'),
        ),
    ]
